server:
  port: 8761
spring:
  profiles: EurekeSer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8762
spring:
  profiles:EurekeSer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/